# Generated by Django 3.2.4 on 2021-06-21 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.product')),
                ('brand', models.CharField(choices=[('AC', 'Acer'), ('AS', 'Asus'), ('LV', 'Lenovo')], max_length=2, null=True)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('display', models.CharField(max_length=20, null=True)),
                ('display_size', models.CharField(max_length=20, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('TR', 'Traditional'), ('LW', 'Lightweight'), ('GM', 'Gaming')], max_length=2, null=True)),
            ],
            bases=('application.product',),
        ),
    ]
