# Generated by Django 3.2.4 on 2021-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210621_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='display',
            field=models.CharField(choices=[('TN', 'Twisted Nematic'), ('IPS', 'In-Plane Switching'), ('OLED', 'Organic Light-Emitting Diode')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(verbose_name='RAM (in gb)'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.IntegerField(verbose_name='Storage (in gb)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price (in php)'),
        ),
    ]
