# Generated by Django 3.2.4 on 2021-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210621_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='graphics_card',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor_brand',
            field=models.CharField(choices=[('AMD', 'AMD'), ('INT', 'Intel')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor_model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (in Kg)'),
        ),
    ]
