# Generated by Django 3.2.4 on 2021-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210621_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='display_size',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='display',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphics_card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
