# Generated by Django 3.2.4 on 2021-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210621_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(choices=[('AC', 'Acer'), ('AS', 'Asus'), ('LV', 'Lenovo'), ('RZ', 'Razer')], max_length=2, null=True),
        ),
    ]
