# Generated by Django 3.2.4 on 2021-06-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_laptop_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
