# Generated by Django 3.2.3 on 2021-06-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_laptop_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.product')),
                ('brand', models.CharField(choices=[('SM', 'Samsung'), ('XM', 'Xiaomi'), ('RM', 'Realme'), ('VV', 'Vivo')], max_length=2, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (in grams)')),
            ],
            bases=('application.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.product')),
                ('brand', models.CharField(choices=[('SM', 'Samsung'), ('XM', 'Xiaomi'), ('RM', 'Realme'), ('VV', 'Vivo')], max_length=2, null=True)),
                ('processor_brand', models.CharField(choices=[('SNP', 'Snapdragon'), ('MDT', 'MediaTek')], max_length=3, null=True)),
                ('processor_model', models.CharField(max_length=100, null=True)),
                ('os', models.CharField(choices=[('A10', 'Android 10'), ('A11', 'Android 11'), ('A12', 'Android 12')], max_length=3, null=True)),
                ('ram', models.IntegerField(verbose_name='RAM (in GB)')),
                ('storage', models.IntegerField(verbose_name='Storage (in GB)')),
                ('display', models.CharField(max_length=100, null=True)),
            ],
            bases=('application.product',),
        ),
    ]
