# Generated by Django 3.2.4 on 2021-06-23 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0013_user_cod_user_credit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_COD',
            new_name='User_Details',
        ),
        migrations.RemoveField(
            model_name='user_credit',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='user_credit',
            name='hs_num',
        ),
        migrations.RemoveField(
            model_name='user_credit',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='user_credit',
            name='province',
        ),
    ]
