# Generated by Django 3.2.3 on 2021-06-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20210623_1703'),
        ('application', '0014_comment'),
    ]

    operations = [
    ]
