# Generated by Django 3.2.4 on 2021-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_merge_0014_auto_20210623_1703_0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='payment_option',
            field=models.CharField(choices=[('None', 'None'), ('Cash On Delivery', 'Cash On Delivery'), ('Credit Card', 'Credit Card')], max_length=50, null=True),
        ),
    ]
